# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Thought of the day
sub_title: The inane ramblings of a software engineer
description: > # this means to ignore newlines until "baseurl:"
  A little blog with my thoughts of the day. Some short, some long. Some about
  tech and web development, some about history, most just inane ramblings.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nagurski.co.uk" # the base hostname & protocol for your site
twitter_username: knagurski
github_username:  knagurski

# Build settings
markdown: kramdown
